# -*- coding: utf-8 -*-
"""Atividade 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uhw2ASYknSjzgdIIxt0O6PWoTamnDU-S
"""

def crie_matriz(n_linhas, n_colunas, valor):
2	    ''' (int, int, valor) -> matriz (lista de listas)
3	
4	    Cria e retorna uma matriz com n_linhas linha e n_colunas
5	    colunas em que cada elemento é igual ao valor dado.
6	    '''
7	
8	    matriz = [] # lista vazia
9	    for i in range(n_linhas):
10	        # cria a linha i
11	        linha = [] # lista vazia
12	        for j in range(n_colunas):
13	            linha.append(valor)
14	
15	        # coloque linha na matriz
16	        matriz.append(linha)
17	
18	    return matriz
19	
20	#-----------------------
21	A = crie_matriz(5,5,0)
22	A[1][1] = 2



